apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: toures-usuario-stateful-mysql
spec:
  selector:
    matchLabels:
      app: toures-usuario-mysql
      tier: mysql
  serviceName: toures-usuario-service-mysql
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app= toures-usuario-mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql-port
  volumeClaimTemplates:
  - metadata:
      name: mysql-volumen
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi