apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: toures-usuario-stateful-mysql
spec:
  serviceName: toures-usuario-service-mysql
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 
    spec:
       containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql_port
        volumeMounts:
        - name: mysql_volumen
          mountPath: ...
  volumeClaimTemplates:
  - metadata:
      name: mysql_volumen
      annotations:
        ...
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi